global:
  resolve_timeout: 5m

route:
  receiver: 'slack'
  group_by: ['alertname']
  repeat_interval: 1m
  routes:
    - match:
        severity: page
      group_by: ['team']
      receiver: 'slack'
      routes:
        - match:
            team: devops
          receiver: 'slack'

receivers:
- name: 'slack'
  slack_configs:
    - channel: "#monitoring_alerting"
      api_url: https://hooks.slack.com/services/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
      text: "Overview: {{ .CommonAnnotations.overview }}"

inhibit_rules:
  - source_match:
      severity: 'page'
    target_match:
      severity: 'ticket'
    equal: ['team']
